dist: bionic
language: python
services:
  - docker
python:
  - "3.7"
before_install:
  - ls /opt/python/
  - /opt/python/3.7.6/bin/python --version
  - sudo apt-get update
  - pip install pycodestyle
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install coverage
  - echo "Prepare for VK test"
  - docker pull homeassistant/home-assistant:0.114.3
  - docker run -d -p 127.0.0.1:8123:8123 --name="home-assistant" -v $TRAVIS_BUILD_DIR/test/travis-ci/HA/:/config -v /etc/localtime:/etc/localtime:ro homeassistant/home-assistant:0.114.3
  - travis_wait 3 sleep 2m
  - export HASS_SERVER=https://127.0.1.1:8123
  - export HASS_TOKEN=.eyJpceyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ93MiOiJhMzRhNjEzMmE5NzM0Yzk1YWYyODU4YjdmN2RjNDIyOSIsImlhdCI6MTU5ODU0NTk1NywiZXhwIjoxOTEzOTA1OTU3fQ.LlhzvCv-orEVipH7HGJxvB304MFJjYYyDNjhT3_egH8
  - pip install homeassistant-cli
  - source <(hass-cli completion bash)
  - hass-cli info
  - hass-cli state list
  - cd /opt
  - deactivate
  - git clone https://github.com/MycroftAI/mycroft-core.git
  - cd mycroft-core
  - cp $TRAVIS_BUILD_DIR/test/travis-ci/Mycroft/dev_setup.sh /opt/mycroft-core/
  - chmod +x dev_setup.sh
  - unset VIRTUAL_ENV
  - ./dev_setup.sh --allow-root --travis -sm
  - mkdir -p /opt/mycroft/skills/homeassistant.mycroftai
  - source /opt/mycroft-core/.venv/bin/activate
  - /opt/mycroft-core/bin/mycroft-pip install -r $TRAVIS_BUILD_DIR/requirements.txt
  - cp -R $TRAVIS_BUILD_DIR/* /opt/mycroft/skills/homeassistant.mycroftai
  - cp $TRAVIS_BUILD_DIR/test/travis-ci/Mycroft/settingsmeta.yaml /opt/mycroft/skills/homeassistant.mycroftai/
  - chmod 0444 /opt/mycroft-core/skills/homeassistant.mycroftai/settingsmeta.yaml
  - /opt/mycroft-core/bin/mycroft-start all
  - travis_wait 6 sleep 4m
  - cd $TRAVIS_BUILD_DIR/
script:
  - echo "Coding style check"
  - pycodestyle --max-line-length=100 __init__.py
  - pycodestyle --max-line-length=100 ha_client.py
  - echo "VKtest"
  - /opt/mycroft-core/bin/mycroft-skill-testrunner vktest clear
  - /opt/mycroft-core/bin/mycroft-skill-testrunner vktest -t homeassistant.mycroftai -i turn
after_success:
