language: python
before_install:
  - sudo apt-get update
  - sudo apt-get -y upgrade
  - sudo apt-get -y install git
  - pip install pycodestyle
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install homeassistant==0.103.6

python:
  - "3.6"
script:
 - pycodestyle --max-line-length=100 __init__.py
 - whoami
after_success:
  codecov
