dist: bionic
language: python
services:
  - docker
python:
  - "3.7"
before_install:
  - ls /opt/python/
  - /opt/python/3.7.6/bin/python --version
  - sudo apt-get update
  - pip install pycodestyle
  - pip install pytest-cov
  - pip install python-coveralls
script:
  - ls -d -1 "$PWD/"*.*
  - echo "Coding style check"
  - pycodestyle --max-line-length=100 __init__.py
  - pycodestyle --max-line-length=100 ha_client.py
  - codecov
  - echo "Prepare for VK test"
  - docker pull homeassistant/home-assistant:0.114.3
  - docker run -d -p 127.0.0.1:8123:8123 --name="home-assistant" -v /PATH_TO_YOUR_CONFIG:/home/travis/build/Tony763/mycroft-homeassistant/test -v /etc/localtime:/etc/localtime:ro homeassistant/home-assistant:0.114.3
  - cd /opt
  - git clone https://github.com/MycroftAI/mycroft-core.git
  - cd mycroft-core
  - git checkout master
  - git pull
  - cp /home/travis/mycroft/skills/homeassistant.mycroftai/test/dev_setup.sh /opt/mycroft-core/
  - chmod +x dev_setup.sh
  - unset VIRTUAL_ENV
  - ./dev_setup.sh --allow-root --travis -sm
  - rm -R /opt/mycroft/skills/homeassistant.mycroftai/
  - cp -R /home/travis/build/Tony763/mycroft-homeassistant/* /opt/mycroft/skills/homeassistant.mycroftai/
  - echo "VKtest"
  - cd /opt/mycroft-core/
  - /opt/mycroft-core/bin/mycroft-skill-testrunner vktest clear
  - /opt/mycroft-core/bin/mycroft-skill-testrunner vktest -t homeassistant.mycroftai
after_success:

