dist: bionic
language: python
services:
  - docker
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - pip install pycodestyle
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install coverage
  # Copy skill befor HA kicks in
  - mkdir -p /opt/mycroft/skills/homeassistant.mycroftai
  - cp -R $TRAVIS_BUILD_DIR/* /opt/mycroft/skills/homeassistant.mycroftai
  # Home-assistant instalation
  - docker pull homeassistant/home-assistant:0.111.4
  - docker run -d -p 127.0.0.1:8123:8123 --name="home-assistant" -v $TRAVIS_BUILD_DIR/test/travis-ci/HA/:/config -v /etc/localtime:/etc/localtime:ro homeassistant/home-assistant:0.114.3
  # Wait for HA to start
  - travis_wait 1 sleep 1m
  - pip install homeassistant-cli
  - export HASS_SERVER=http://127.0.0.1:8123
  - export HASS_TOKEN='eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmMzI5NmEzYTA0ZDc0NTI3OGUzMDIzN2I5MDlmYmM5MSIsImlhdCI6MTU5ODczMzU5MywiZXhwIjoxOTE0MDkzNTkzfQ.HEGTdkF5tt473J3WktjUIb71x06tZwcZUjp070QzLec'
  - source <(hass-cli completion bash)
  - hass-cli info
  - hass-cli state list
  # Mycroft instalation
  - cd /opt
  - deactivate
  - git clone https://github.com/MycroftAI/mycroft-core.git
  - cd mycroft-core
  # Apply de_setup.sh silent mode fix
  - cp $TRAVIS_BUILD_DIR/test/travis-ci/Mycroft/dev_setup.sh /opt/mycroft-core/
  - chmod +x dev_setup.sh
  - unset VIRTUAL_ENV
  - ./dev_setup.sh --allow-root --travis -sm
  - source /opt/mycroft-core/.venv/bin/activate
  - /opt/mycroft-core/bin/mycroft-pip install -r $TRAVIS_BUILD_DIR/requirements.txt
  # Apply skill test settings
  - cp $TRAVIS_BUILD_DIR/test/travis-ci/Mycroft/settingsmeta.yaml /opt/mycroft/skills/homeassistant.mycroftai/
  - cp $TRAVIS_BUILD_DIR/test/travis-ci/Mycroft/settings.json /opt/mycroft/skills/homeassistant.mycroftai/
  # Back into build dir
  - cd $TRAVIS_BUILD_DIR/
script:
  # Coding style check
  - mkdir log
  - pycodestyle --max-line-length=100 __init__.py >> ./log/__init__.log
  - pycodestyle --max-line-length=100 ha_client.py >> ./log/__ha_client__.log
  # VKtest
  - /opt/mycroft-core/bin/mycroft-skill-testrunner vktest clear
  - /opt/mycroft-core/bin/mycroft-skill-testrunner vktest -t homeassistant.mycroftai -f allure_behave.formatter:AllureFormatter -o ./allure_results
  # Generate Allure report
  - python3 -m allure generate /opt/mycroft-core/test/integrationtests/voight_kampff/allure-results --clean -o allure-report
  # Send report somewhere
  - cd /opt
  - git clone https://github.com/Tony763/Tony763.github.io.git
  - cd Tony763.github.io
  - mkdir -p $TRAVIS_COMMIT/
  - cp -r $TRAVIS_BUILD_DIR/log .
  - cp -r $TRAVIS_BUILD_DIR/allure-report .
  - git add .
  - git commit -m "Travis CI results for "$TRAVIS_COMMIT
  - git push
after_success:
