language: python
services:
  - docker
before_install:
  - sudo apt-get update
  - pip install pycodestyle
  - pip install pytest-cov
  - pip install python-coveralls
install:
  - ls -d -1 "$PWD/"*.*
  - mkdir -p /home/travis/mycroft/skills/homeassistant.mycroftai
  - mkdir -p /home/travis/mycroft/config
  - ln -s /home/travis/build/*/*/ /home/travis/mycroft/skills/homeassistant.mycroftai/
  - docker pull homeassistant/home-assistant:0.114.3
  - docker run -d -p 127.0.0.1:8123:8123 --name="home-assistant" -v /PATH_TO_YOUR_CONFIG:/home/travis/mycroft/skills/homeassistant.mycroftai/test -v /etc/localtime:/etc/localtime:ro homeassistant/home-assistant:0.114.3
  - docker pull mycroftai/docker-mycroft
  - docker run -d -v config_dir_on_host:/home/travis/mycroft/config -v skills_dir_on_host:/home/travis/mycroft/skills --device /dev/snd -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native -v ~/.config/pulse/cookie:/root/.config/pulse/cookie -p 8181:8181 --name mycroft mycroftai/docker-mycroft
  - echo "Wait for start of HA and Mycroft in background"
  - travis_wait 12 sleep 5m
python:
  - "3.6"
script:
  - echo "Coding style check"
  - pycodestyle --max-line-length=100 __init__.py
  - pycodestyle --max-line-length=100 ha_client.py
  - echo "VKtest"
  - docker exec mycroft /bin/bash -c "cd /opt/mycroft/;ls -d -1 *; ls -d -1 ./bin/;  source /opt/mycroft/.venv/bin/activate; /opt/mycroft/bin/mycroft-skill-testrunner vktest  clear, /opt/mycroft/bin/mycroft-skill-testrunner vktest -t homeassistant.mycroftai; exit"
after_success:
  - codecov
