language: python
services:
  - docker
before_install:
  - sudo apt-get update
  - pip install pycodestyle
  - pip install pytest-cov
  - pip install python-coveralls

python:
  - "3.6"
script:
 - ls -d -1 "$PWD/"*.*
 - pycodestyle --max-line-length=100 __init__.py
 - pycodestyle --max-line-length=100 ha_client.py
after_success:
  codecov
