language: python
before_install:
  - pip install pycodestyle
  - pip install pytest-cov
  - pip install python-coveralls
python:
  - "3.6"
script:
 - pycodestyle --max-line-length=100 __init__.py
 - pytest --rootdir=unittests --cov unittests/
after_success:
  codecov
